### ISSUE TITLE
[Bug] Some features can be generated in lava

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#10]
### What happened?

Some features can be placed in lava, probably they don't have air check
![2022-06-16_19 38 41](https://user-images.githubusercontent.com/17707380/174122014-d7c1b01c-24c5-4868-8514-9a45173eb014.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
No output
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
