### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by Leggyiscool** [quiqueck/BetterNether#100]
I download the mods and when i open creative, i see the better nether and end mod things. I can spawn them in. However, the tools wont do dmg or if i try to mine blocks with them the blocks just reappear. When i go to the end or nether they are the same. Please tell me how i can fix it.

**Comment by quiqueck** [comment]
Thanks for reporting :)

Are you playing on a server? 
This sound like issue you would get if you play with fabric mods on an unmoved server...
