### ISSUE TITLE
[Bug] Incompatibility with Marium's Soulslike Weaponry

### ISSUE THREAD

**Issue by ZeroKun265** [quiqueck/BetterNether#102]
### What happened?

While running a server with friends we noticed that some mobs from the Marium's Soulslike Weaponry mod were not spawning, specifically the withered demons.
I decided to check what was the problem myself

## Test 1
**Minecraft:** 1.18.2
**Fabric loader:** 0.14.10
**Marium's Soulslike Weaponry:** 0.9.7
**Gecko Lib(dependency):** 3.0.77

While looking in the crimson forests, where the withered demons should spawn, i was able to find a couple(with the aid of execute command and glowing effect)

## Test 2
**Minecraft:** 1.18.2
**Fabric loader:** 0.14.10
**Marium's Soulslike Weaponry:** 0.9.7
**Gecko Lib(dependency):** 3.0.77
**Better Nether:** 6.1.2
**BCLib:** 1.4.7

While looking in the crimson forests, where the withered demons should spawn, i was NOT able to find any( even with the aid of execute command and glowing effect as before)

I don't know if the issue is on the side of Better Nether or Marium's Soulslike Weaponry or mine, so i'll also comment in the curseforge page for Marium's Soulslike Weaponry (they do not have any other way of giving issues by they seem to respond) linking the issue as well

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.59.1+1.18.2

### Fabric Loader

0.14.10

### Minecraft

1.18.2

### Other Mods

```shell
Marium's Soulslike Weaponry
Gecko Lib
```

**Comment by quiqueck** [comment]
I am very sorry, but currently we will not update mod compatibility for the 1.18 versions. :(
