### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by Cha0ticNoise** [quiqueck/BetterNether#105]
### What happened?

I've started a new server with the modpack names medievalcraft and when I try to join the server it says the recipient has an id not recognized 
"Registry remapping failed: Received ID map for Minecraft:item contains IDs unknown to the receiver! - better nether:spawn_egg_naga"

### BetterNether

7.1.2

### BCLib

2.1.5

### Minecraft

1.19.2

### Other Mods

```shell
https://www.curseforge.com/minecraft/mc-mods/franciscofunari
```

**Comment by quiqueck** [comment]
This usually means, that the mod-versions  / -configs on client and server are not in sync.

**Comment by Cha0ticNoise** [comment]
I've used the same packs and everything so I'm assuming maybe some config stuff 
Do you have an idea to fix it?

**Comment by quiqueck** [comment]
Did you change the default configs? That is known to cause problems.

**Comment by DerOliDE** [comment]
We've the same problem with 7.1.3, maybe related to this: https://github.com/FabricMC/fabric/issues/2168

I'm not that deep in fabric, as I understand it, they've change something with the registry sync between client and server.

**Comment by quiqueck** [comment]
Thanks for that link, but our Mods have to be present on Server and Client to work properly. As far as I can tell, the issue linked issue is about Server-Only Mods.

**Comment by quiqueck** [comment]
But, if you have another server-only mod installed that may be  trigger the problem
