### ISSUE TITLE
[Bug] Vines generates only bottom blockstate

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#11]
### What happened?

All vines are generated from only one blockstate - bottom, ignoring other middle states
![2022-06-16_19 40 54](https://user-images.githubusercontent.com/17707380/174122732-72d7a28d-06b3-43e3-92a1-245ff5e4ba50.png)
Updating blocks fixes issue, this means that the bug is in feature generation
![2022-06-16_19 41 43](https://user-images.githubusercontent.com/17707380/174122860-a362facb-fdfe-4c56-83d7-b761c6abc307.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
No logs
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
