### ISSUE TITLE
[Bug] Barrel cactuses placed only in the first stage

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#12]
### What happened?

All barrel cactuses are placed as a starting non-grown cactus. Other cactuses (like agava) are placed randomly (as they should)
![2022-06-16_19 44 06](https://user-images.githubusercontent.com/17707380/174123477-340ae776-fbee-4e3a-bee0-ea243eccaf54.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
No logs
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
