### ISSUE TITLE
[Bug] Cincinnasite Fire Bowls of all variants have an under-block opacity issue.

### ISSUE THREAD

**Issue by BillyByrns** [quiqueck/BetterNether#123]
### What happened?

Any/all of the Fire Bowls, when placed down, make the top of the block immediately below them completely invisible.

Not game breaking, but unpleasant; especially because the Netherite Soul ones are my favorite, and they look so sick. And they provide ample light, for a compact soul-fire source! Thanks for making it. Hope it can be patched soon. :)

### BetterNether

7.1.3

### BCLib

2.1.6

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
I think this might be a duplicate of #137. Do you by any chance have MoreCulling installed?
