### ISSUE TITLE
[Bug] leaves not properly textured

### ISSUE THREAD

**Issue by ghost** [quiqueck/BetterNether#124]
### What happened?

![image](https://user-images.githubusercontent.com/128465747/226556322-012d1cc8-3547-4dff-9cd6-96f79369896c.png)

all leaves variants in better nether (+ end) are not rendering/texturing properly, the gaps that are supposed to be present in the texture between the leaves are filled in with black or white, and the nether sakura leaves have the worst of the bug because it looks nothing like how its supposed to

### BetterNether

7.1.2

### BCLib

2.1.6

### Fabric API

0.75.1

### Fabric Loader

0.14.17

### Minecraft

1.19.2

### Other Mods

oh the biomes you'll go, biome makeover, incendium, ecologics, deeper and darker, awesome dungeons end + ocean, better end, dungeons arise, regions unexplored, rei, jade, xaero's world map + mini map

**Comment by quiqueck** [comment]
Did you by any chance set your rendering to fast?

**Comment by ghost** [comment]
it was on fast, and setting it to fancy fixed it! thanks
