### ISSUE TITLE
[Bug] Nether Sakura can generate detached blocks

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#13]
### What happened?

Sometimes (in ~40% cases) Nether Sakura can be generated with detached leaves at the crown tip
![2022-06-16_19 48 17](https://user-images.githubusercontent.com/17707380/174124141-d2bf10ad-a4ae-47f0-a228-9ceb3bdb3d0c.png)
![2022-06-16_19 48 31](https://user-images.githubusercontent.com/17707380/174124146-f72c9060-5753-47c5-b4a6-c7515ee941a1.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Fixed in 7.0.4
