### ISSUE TITLE
[Bug] Giant Lucis block and Lucis plant bug

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterNether#139]
### What happened?

Giant lucis block and lucis plant have a visual bug and does not have colission.
![2023-06-22_23 08 39](https://github.com/quiqueck/BetterNether/assets/86960084/b2b0a92d-9ca1-4dc0-b741-8675528ffea0)
![2023-06-22_22 52 43](https://github.com/quiqueck/BetterNether/assets/86960084/1d457a89-649e-4002-af5a-e08ee0d76bee)

### BetterNether

9.0.6

### BCLib

3.0.9

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Should be fixed in BetterNether 9.0.7.
