### ISSUE TITLE
[Bug] Many nether city chest/drawers are empty

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterNether#141]
### What happened?

Not sure if this is intended, but many drawers and chests in the nether city are empty. My suggestion for balancing the loots as there are many chests and drawers in the nether city are different chests/drawers have different level/rarity of loot, one with a skeleton spawner have a better loot. Finding chests/drawers (loots) are part of the fun in exploring the nether cities😃
![2023-06-22_23 54 26](https://github.com/quiqueck/BetterNether/assets/86960084/90f62c19-438c-43b0-a6f6-48c9d89dd154)
![2023-06-22_23 55 29](https://github.com/quiqueck/BetterNether/assets/86960084/a9f07df0-3941-4b55-9a5a-96fb63d26382)

### BetterNether

9.0.6

### BCLib

3.0.9

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Thanks for reporting, there should not be empty chests/barrels. I have to check our structure files :)

**Comment by quiqueck** [comment]
Should be fixed in BetterNether 9.0.7.
