### ISSUE TITLE
[Bug] Drops from ores like nether lapis, nether ruby and cincinatti ore don't drop

### ISSUE THREAD

**Issue by mhkdepauw** [quiqueck/BetterNether#143]
### What happened?

 Drops from ores like nether lapis, nether ruby and cincinatti ore don't drop when mining with a modded pickaxe of a sufficiently high tier. I used Hephaestos tools that are netherite tier or higher and you can mine the ores very easily but you don't get any drops. (1.18.2)

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.76.0

### Fabric Loader

0.14.19

### Minecraft

Older

**Comment by quiqueck** [comment]
Due to limited resource, we no longer support 1.18.2

**Comment by mhkdepauw** [comment]
There's no reason to believe this bug has been fixed in the newer versions unless the code for those was completely rewritten, I'll check it out when I have time

**Comment by JackoDynamics** [comment]
This bug is still present in 1.20.1
