### ISSUE TITLE
Green lines in a radius around me

### ISSUE THREAD

**Issue by RiuWaystone** [quiqueck/BetterNether#145]
### What happened?

Green lines are constantly visible. they are not stationary, they are rendered in a radius around me. They change when i move my camera and when moving the player.
![image](https://github.com/quiqueck/BetterNether/assets/61890064/9b0eed79-eb4e-430d-a04d-47f00477308e)
![image](https://github.com/quiqueck/BetterNether/assets/61890064/31edb8c5-287e-4efc-91c0-9879bf803db7)
![image](https://github.com/quiqueck/BetterNether/assets/61890064/84e9c66a-528b-4698-b7b8-90d613dcb8ee)

### BetterNether

7.1.4

### BCLib

2.1.7

### Fabric Loader

0.14.21

### Minecraft

1.19.2

### Other Mods

```shell
no other mods!
```

**Comment by quiqueck** [comment]
Did you change your graphics mode to fast? Because that could cause aliasing artefacts. BetterNether should otherwise not change the rendering in the overworld.

**Comment by RiuWaystone** [comment]
Ok yes, going up to fancy fixed it. **Thanks for the quick help :)** 
It's weird though, it clearly only happens when better nether (or better end) is activated. Without it everything looks fine even on fast.
