### ISSUE TITLE
[Bug] Density of stalactites in some biomes is too large

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#15]
### What happened?

Density of stalactites in some bioms is too high, as a result the whole ceiling is covered with stalactites
![2022-06-16_19 50 06](https://user-images.githubusercontent.com/17707380/174124911-e3090fcb-2160-457d-80a1-561507392e57.png)
![2022-06-16_19 52 44](https://user-images.githubusercontent.com/17707380/174124914-32ab94b9-f050-4946-ab64-e5b1d2a91f12.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
