### ISSUE TITLE
[Bug] Cincinnasite should be able to be used in stonecutter

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterNether#150]
### What happened?

I think cincinnasite should be able to be used in stonecutter. BN Blocks that don't have stonecutter recipe: Basalt bricks, Soul sandstone, BN nether brick variants (roof tile, large brick tile, small brick tile, wall, stairs), Ruby block

### BetterNether

7.1.4

### BCLib

2.1.7

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
Thanks for the report. I think I found all missing recipes. Changes should be available in  BetterNether 9.0.8. Please let me know if I missed something...
