### ISSUE TITLE
[Bug] Firefly body don't have tint

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#16]
### What happened?

Firefly don't have colored ting - their body is white when their glow is colored. Bug exists in both 1.18.2 and 1.19
![2022-06-16_19 55 14](https://user-images.githubusercontent.com/17707380/174125303-300e749b-28fe-4776-856d-ef5dbd30ce77.png)

Correct shading (with tint) should look like this:
![image](https://user-images.githubusercontent.com/17707380/174125701-58f86216-8949-4d3d-8d36-1cf85a523a5a.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
