### ISSUE TITLE
[Bug] crash with End Hammer from Gobber2

### ISSUE THREAD

**Issue by Fury94-Echo** [quiqueck/BetterNether#17]
### What happened?

client crash when i use hammer hit entitie
[crash-2022-06-17_00.46.52-client.txt](https://github.com/quiqueck/BetterNether/files/8920927/crash-2022-06-17_00.46.52-client.txt)
s

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.7

### Minecraft

1.19

### Other Mods

```shell
gobber2 bclib better nether  etc in the log
```

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
