### ISSUE TITLE
[Bug] Random patches of overworld blocks

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#18]
### What happened?

I'm not sure if it is an issue or it is intended, but there are some random patches of overworld blocks in some Nether places
![2022-06-16_19 59 46](https://user-images.githubusercontent.com/17707380/174126757-2af79a0c-795c-478f-909f-0c4c4328f1b8.png)
![2022-06-16_20 01 24](https://user-images.githubusercontent.com/17707380/174126766-7dc3f484-a753-4fd3-aca8-2067ecfd37ea.png)
![2022-06-16_20 02 03](https://user-images.githubusercontent.com/17707380/174126769-3cafc7bc-4b60-4529-b214-78dde9b1e83c.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Those are actually intended.
