### ISSUE TITLE
[Bug] Nether cities can be generated inside fortresses

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#19]
### What happened?

Old BN had a code that prevent this, new one - not
![2022-06-16_20 13 00](https://user-images.githubusercontent.com/17707380/174128617-66967dd6-0fc3-4f6b-8221-0e3fb3a936d4.png)

### BetterNether

7.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-end-2.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by paulevsGitch** [comment]
Another similar city
![2022-06-16_20 17 37](https://user-images.githubusercontent.com/17707380/174129289-928dfb69-c494-4215-a594-4563cd4886b0.png)

**Comment by quiqueck** [comment]
This is probably similar to #6 and might be due to a faulty BoundingBox.
