### ISSUE TITLE
Buttons have a coliss

### ISSUE THREAD

**Issue by Redd56** [quiqueck/BetterNether#2]
### What happened?

Buttons (all of them that better nether implement) have a collision model that collides with entities. Meaning many things that buttons are useful for that arent just being a button you press (a block to prevent spawning in nether highways being one). are not possible
this is unlike vanilla buttons which do not have a collision model. and entities act as if it is air.

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.53.4

### Fabric Loader

0.14.6

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Thanks for reporting. This issue should be fixed in the next release for 1.18.2/1.19.

**Comment by Redd56** [comment]
Thx. Cant wait for the update to drop
