### ISSUE TITLE
[Bug] Eye Seed can be used to break bedrock

### ISSUE THREAD

**Issue by Zunwolf1896** [quiqueck/BetterNether#24]
### What happened?

A player of mine figured out you can break bedrock using the Eye Seed and reported it to me using the following video.

https://user-images.githubusercontent.com/88537204/175808109-b373290f-ac0f-4070-9d08-2f1a3fab4096.mp4

### BetterNether

7.0.2.jar

### BCLib

2.0.5.jar

### Fabric API

0.56.1+1.19

### Fabric Loader

0.14.7

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting. This should be fixed in the next update

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
