### ISSUE TITLE
Black glazed terracotta generates at the base of blackstone stlagtite... ;-;

### ISSUE THREAD

**Issue by DiePutin3782** [quiqueck/BetterNether#26]
Bug #1: Is this intentional??
![2022-06-28_13 42 17](https://user-images.githubusercontent.com/90800816/176248381-d6b988f3-ec46-41d6-af91-4d848854df28.png)
![2022-06-28_13 41 52](https://user-images.githubusercontent.com/90800816/176248404-32abaa72-40e8-4e27-9b57-752282e0b951.png)
Why is there black glazed terracotta instead of blackstone at the base of a blackstone stlagtite, is this a bug or...

**Comment by quiqueck** [comment]
Yes
