### ISSUE TITLE
[Bug] Moss can generate in the air

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#29]
### What happened?

Moss in Nether Jungle can generate in the air, updating blocks will cause it to collapse (screenshot is not very good, but some moss parts are in the air)

![2022-06-30_14 25 50](https://user-images.githubusercontent.com/17707380/176669278-f36382f9-2350-449d-9a2b-9f82efe744b6.png)

### BetterNether

7.0.3

### BCLib

2.0.6

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
better-end-2.0.3
eden-ring-0.6.3
enderscape-0.3.0
geckolib-fabric-1.19-3.1.2
iris-mc1.19-1.2.5
mantori-1.1.0-1.19
modmenu-4.0.0
sodium-fabric-mc1.19-0.4.2+build.16
worldedit-mod-7.2.11-beta-01
```

**Comment by quiqueck** [comment]
Fixed in 7.0.4
