### ISSUE TITLE
[Bug] Mushrooms are tall

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterNether#30]
### What happened?

Res mushrooms in forests are tall, looks like they are 2-3 times taller than they should be

![2022-06-30_14 35 42](https://user-images.githubusercontent.com/17707380/176669806-bd911ed4-7a4c-4724-8c61-3b1a798eee87.png)

In older versions:

![image](https://user-images.githubusercontent.com/17707380/176670786-4c3e4538-7633-4b08-9294-379bfc263d25.png)

### BetterNether

7.0.3

### BCLib

2.0.6

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
better-end-2.0.3
eden-ring-0.6.3
enderscape-0.3.0
geckolib-fabric-1.19-3.1.2
iris-mc1.19-1.2.5
mantori-1.1.0-1.19
modmenu-4.0.0
sodium-fabric-mc1.19-0.4.2+build.16
worldedit-mod-7.2.11-beta-01
```

**Comment by quiqueck** [comment]
This was actually intentional in the re-design.
