### ISSUE TITLE
[Bug] Mod cannot be downloaded by Non-Curseforge launchers

### ISSUE THREAD

**Issue by DDriggs00** [quiqueck/BetterNether#31]
### What happened?

The curseforge setting for disabling Third-Party launchers appears to be enabled. This causes the mod to be impossible for any launcher except the OverWolf launcher. Would it be possible to correct this setting?

### BetterNether

6.1.2

### BCLib

N/A

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Sure
