### ISSUE TITLE
[Bug] Ruby ore is not dropping rubies

### ISSUE THREAD

**Issue by Sepiks-9** [quiqueck/BetterNether#32]
### What happened?

Cannot obtain rubies from breaking nether ruby ore.

### BetterNether

7.0.5

### BCLib

2.0.10

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Do you use netherite gear?

**Comment by Sepiks-9** [comment]
> Do you use netherite gear?

Does it require netherite to mine? If so, no I didn't use netherite.

**Comment by quiqueck** [comment]
Jup,  currently it needs netherite level tools
