### ISSUE TITLE
[Bug] Mining Rubies only drops xp

### ISSUE THREAD

**Issue by BenR184** [quiqueck/BetterNether#35]
### What happened?

When I mine ruby ore in the nether, using diamond pick, only xp orbs are dropped.

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric Loader

0.14.6

### Minecraft

1.18.2

### Other Mod 

Im using CurseForge, and BetterMinecraft.

**Comment by quiqueck** [comment]
Hi, and thanks for contacting us. 
Rubies need netherite level gear to be mined (similar issue to #32)
