### ISSUE TITLE
[Bug] Sculk replaces ALL netherrack in the nether swampland!

### ISSUE THREAD

**Issue by DiePutin3782** [quiqueck/BetterNether#36]
### What happened?

![2022-07-09_19 01 34](https://user-images.githubusercontent.com/90800816/178125316-04ce449e-0b1d-493a-bb1f-3636300baad3.png)
I don't need to explain much... This screenshot says it all...
This a bug???

### BetterNether

7.0.5

### BCLib

2.0.10

### Fabric API

0.57.0

### Fabric Loader

1.14.8

### Minecraft

1.19

### Relevant log output

```shell
N/A
```

### Other Mods

```shell
Better End
Fabric API
Chunky
Fabric Tree Chopper
Lag Removal
Luck Perms
Minecraft Command Permissions (related to Luck Perms)
```

**Comment by quiqueck** [comment]
It is intentional but will be rolled back in the next release
