### ISSUE TITLE
[Suggestion] Add Vine, Plant and Staltite spawnrates to config.

### ISSUE THREAD

**Issue by xVanquishx** [quiqueck/BetterNether#41]
### Description

I really like most of the BetterNether, however Vines to be a bit hurtful on the eye when the generate in huge amounts, and being able to reduce plant and stalagmites would greatly help the feel of traversal I want as well,

**Comment by quiqueck** [comment]
This config was moved to Datapacks, and BetterNether will eventually ship with one that reduces the vegetation spawn.

However you can easily build your own. As a starting point you can export most needed files using `/bclib dump_datapack`. If you check the `betternether/worldgen/configured_Feature` and `placed_feature` folders you will find the settings for all vegetation types. Changing and moving them to a datapack will override our built-in settings.

Just out of curiosity, which biome do you think about? Maybe it needs  adjustments in general.

**Comment by xVanquishx** [comment]
Ah, not really used to datapacks XD.

~~ Unfortunately, "default" datapacks don't exist, so when you have a lot of mods, it's hard to figure what to do in a Datapack, but yeah Datapacks allow world-specific changes. ~~ Strike this, cause now I know what bclib dump_datapack does.

Personally, I'd need to experiment with vines, cause it's too bright and saturates the screen but reducing it might make it look weird. For Stalagmites, I would make it sparce and only exist in areas with a low ceiling. For Plants, would reduce it most biomes except soul plains and grasslands. I've also straight out disabled magma lands and old fungiwoods. So, a lot of is personal preference, so I guess it depends on developer's vision.

**Comment by xVanquishx** [comment]
hmmm, both the configuredfeatures and placedeatures folder are empty

**Comment by quiqueck** [comment]
Oh? That would be a Bug then :) I'll check later...

**Comment by quiqueck** [comment]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/280847/180485763-0d9727ab-3911-4173-a4d0-426c45185317.png">
Hm, just tested and for me the files get properly generated.

**Comment by xVanquishx** [comment]
hmmmmm, all other folders are generating correctly 
![image](https://user-images.githubusercontent.com/29439049/180610629-19a80fb7-aa30-4568-9c48-49547c3c0379.png)

**Comment by xVanquishx** [comment]
Could it be a compatibility issue with Quilt? Or prolly another mod.

**Comment by quiqueck** [comment]
Check the logs and search for the `configured_feature` part. Does it show any errors related to those?

**Comment by xVanquishx** [comment]
`[00:27:37] [Server thread/ERROR]: [bclib]       ->> Unable to encode: class net.minecraft.class_2975 cannot be cast to class net.minecraft.class_6885 (net.minecraft.class_2975 and net.minecraft.class_6885 are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @c7045b9)
[00:27:37] [Server thread/INFO]: [bclib]    - C:\Users\xVanq\AppData\Roaming\PolyMC\instances\Modpack With WorldGen Changes\.minecraft\bclib_datapack_dump\betternether\worldgen\configured_feature\golden_lumabus_vine.json
`

Seems to be recurring alot, and yeah seems to be based on quilt

**Comment by quiqueck** [comment]
Ah, ok that appears to be a quilt thing :(

**Comment by xVanquishx** [comment]
hey, it doesn't seem to be a quilt thing, seems to also happen on fabric,

`[06:59:04] [Server thread/ERROR]: [bclib]       ->> Unable to encode: class net.minecraft.class_2975 cannot be cast to class net.minecraft.class_6885 (net.minecraft.class_2975 and net.minecraft.class_6885 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c0ecd4b)
[06:59:04] [Server thread/INFO]: [bclib]    - C:\Users\xVanq\AppData\Roaming\PolyMC\instances\Modpack With WorldGen Changes\.minecraft\bclib_datapack_dump\minecraft\worldgen\configured_feature\mega_pine.json`

Must be a mod conflict with bclib

**Comment by quiqueck** [comment]
I am not sure if this will help, but I am now serialising the data differently (BCLIb 2.0.17 and up). Maybe that will work with quilt as well.

**Comment by quiqueck** [comment]
The changes should be available now in 2.0.17. Please re-open the issue if there are still problems our if you need further assistance.
