### ISSUE TITLE
[Bug] Nether Ruby ore isn't dropping anything when mined.

### ISSUE THREAD

**Issue by RogerWilco80** [quiqueck/BetterNether#42]
### What happened?

When mining nether ruby ore, it isn't dropping anything. We've tried diamond, and iron pickaxes both with and without silk touch.

### BetterNether

7.0.6

### BCLib

2.0.15

### Fabric API

0.57.0+1.19

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
waystones-fabric-1.19-11.0.1
inmis-2.7.0-1.19
EmeraldTools-Fabric-1.19.0-1.4.14
cloth-config-7.0.73-fabric
balm-fabric-4.3.0+0
```

**Comment by quiqueck** [comment]
You need netherite level tools to mine Rubies
