### ISSUE TITLE
How to create blue obsidian?

### ISSUE THREAD

**Issue by Sparrow-Moon** [quiqueck/BetterNether#44]
### Description

Okay, not a suggestion, and i created an account because i cant find the answer anywhere else
How do i go about creating the blue obsidian? I love the look of it, but i cant figure out how to create it using the soulsand/stone
Please help, I just want the block

**Comment by quiqueck** [comment]
If a lava source over soul-sand turns into obsidian, you will get the blue one: https://media.forgecdn.net/attachments/405/917/blueobsidian.gif

Or you can find a magma land biome in the Nether. It will spawn naturally there.

**Comment by Sparrow-Moon** [comment]
> 

Thank you so much!
