### ISSUE TITLE
[Bug] No Incendium Biomes

### ISSUE THREAD

**Issue by ArEsGtH** [quiqueck/BetterNether#45]
### What happened?

It seems uncompatible with Incendium mod.

### BetterNether

6.12

### BCLib

1.4.7

### Fabric API

0.57.0

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Please have a look at this:
https://github.com/quiqueck/BCLib/issues/24#issuecomment-1191810517

It is a similar Problem.
