### ISSUE TITLE
Leads/Breeding for Flying Pigs

### ISSUE THREAD

**Issue by fungalgills** [quiqueck/BetterNether#5]
### What happened?

When I first saw a Flying Pig, I was instantly motivated to befriend it. Realizing I couldn't ride it and wasn't sure how to lure it, I whipped out a trusty Lead and was excited to see it connect. The bat's flight patterns weren't altered, though, and it was as if the lead wasn't there at all. Eventually it snapped, but it stretched a surprising amount beforehand. I think being able to lead Flying Pigs would be a nice feature, and if they have a food to lure/breed them with knowing that would be cool as well. 

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.55.1

### Fabric Loader

0.14.6

### Minecraft

1.18.2

### Other Mods

```shell
Roughly enough items
Origins, added origins, mob origins, extra origins
BetterEnd
Pehkeui
Xaero's minimap

Cloth config API, Architectury API
```

**Comment by quiqueck** [comment]
Accepted, and added to the Enhancement Project. I will post here when there are any updates.
