### ISSUE TITLE
[Suggestion] Config option to remove "Survives on: ..." text

### ISSUE THREAD

**Issue by Shadowdragon019** [quiqueck/BetterNether#51]
### Description

I also suggest having this be removed by default, I suggest this as with it enabled it removes some experimentation aspects of Better Nether.

When you want to know which block this is placed on you read a block of text instead of experimenting yourself, which I feel negatively impacts the user-experience.

![image](https://user-images.githubusercontent.com/67480398/186248283-64869051-a536-42d6-8312-0f0a833b63ee.png)

**Comment by DanCodesRBX** [comment]
I second this

**Comment by quiqueck** [comment]
Will be a setting in BCLib in the next version.

**Comment by quiqueck** [comment]
Added to BCLib 2.1.1
