### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BigSmartBear** [quiqueck/BetterNether#53]
### What happened?

Fireflies break with almost any shader

### BetterNether

7.1.0

### BCLib

2.1.0

### Fabric API

0.58.0

### Fabric Loader

0.14.9

### Minecraft

1.19

### Relevant log output

```shell
n/a
```

### Other Mods

```shell
iris / optifine
```

**Comment by paulevsGitch** [comment]
Shader issues are shader issues, they are not related to the mod. Use mod-friendly shaders like Complementary

**Comment by Drezkil** [comment]
> Shader issues are shader issues, they are not related to the mod. Use mod-friendly shaders like Complementary

Bruh man it does with complementary too
