### ISSUE TITLE
[Bug] missing biomes

### ISSUE THREAD

**Issue by elgordo42** [quiqueck/BetterNether#57]
### What happened?

biomes are are missing.
Running 1.19.2 all the latest (can only chose 19.1 here).
I have followed https://github.com/paulevsGitch/BetterNether/issues/293  but it won't work. have tried with and without bclib biome fix enabled.
Either the game crash or I will stand in the portal for all eternity. 
Have tried with and without other mods loaded. same...
Out of ideas.

### BetterNether

7.1.0

### BCLib

2.1.0

### Minecraft

1.19.1

**Comment by quiqueck** [comment]
Thanks for reporting. The fix you mention is not intended for 1.19 Versions of our Mods. 

Could you please attach a full log (you can upload it as a reply to this issue)? Could you please also run the command `/bclib print dimensions` and send the output.
