### ISSUE TITLE
[Bug] Incompatible with mods that make crying obsidian valid portal blocks

### ISSUE THREAD

**Issue by SplendidAlakey** [quiqueck/BetterNether#59]
### What happened?

When BetterNether is installed, mods that let you build portals using crying obsidian blocks don't work.

If the incompatibility is not possible to fix, then a "simple" solution would be to implement this feature in BN itself.

### BetterNether

7.1.0

### BCLib

2.1.0

### Fabric API

0.61.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Other Mods

```shell
Example mods that don't work with BetterNether: Crying Portals (https://www.curseforge.com/minecraft/mc-mods/crying-portals-fabric); Charm (https://www.curseforge.com/minecraft/mc-mods/charm).
```

**Comment by quiqueck** [comment]
Thanks for reporting. 

You can already do this with a simple Datapack. BCLib introduces a new Tag `c:nether_pframe`every Block with that tag is considered a valid Portal Frame in BetterNether.

Let me know if you need some help with that...

**Comment by SplendidAlakey** [comment]
Yes, please, I'd like an example datapack, because I have no idea where to put what. I tried looking up adding tags to blocks via datapacks and, frustratingly, found nothing other than editing vanilla tags jsons.

And should this issue stay open or should I close it?

**Comment by quiqueck** [comment]
[portal.zip](https://github.com/quiqueck/BetterNether/files/9739940/portal.zip)
This is a simple DataPack that will add the vanilla crying obsidian as well as coal ore as a portal frame. 

If that is everything you need, then you can close the issue. Otherwise feel free to ask your questions here :)

**Comment by SplendidAlakey** [comment]
Got it, thanks. I actually almost understood it then, I just didn't know what to call the json file, since the tag itself included a `:`. Now I know that you only need whatever is after it. Although I had to repackage your example pack, because I can only use datapacks that don't throw the data folder and the mcmeta file into a subfolder within the archive.

In any case, it works. Thanks again!
