### ISSUE TITLE
[Bug] Floaty lucis spores when a nether city is in a Nether Mushroom biome

### ISSUE THREAD

**Issue by aisukuma** [quiqueck/BetterNether#6]
### What happened?

Floaty lucis spore blocks are seen above a nether city when they are in a nether mushroom biome.

![2022-06-14_00 22 59](https://user-images.githubusercontent.com/22802219/173493013-e3c4ca32-2bd0-472a-9734-e8eeb13d442e.png)

### BetterNether

7.0.1

### BCLib

2.0.4

### Fabric API

0.53.3+1.19

### Fabric Loader

0.14.7

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thank you for reporting. Do you happen to have the world seed/position? That would help me debug the issue :).

**Comment by aisukuma** [comment]
Hi! Unfortunately I deleted that world, but I made a new one and found a nether city in a nether mushroom biome that had the same issue.

Seed: 1321035535288586205
Coordinates: -973 80 4396

**Comment by quiqueck** [comment]
Should be fixed in the just release 7.0.3 update.
