### ISSUE TITLE
[Bug] Too Much Ruby

### ISSUE THREAD

**Issue by drakolordx7** [quiqueck/BetterNether#60]
### What happened?

It seems ruby spawn rates are far too high.
In my survival world I made it to the nether and in my starting area found over 64 ruby, thats clearly disbalanced considering its stronger than netherite.
I adjusted the config and it was fine but I dont understand why the defualt is so high, or if something is causing it be disproportionately spawned.

### BetterNether

7.1

### BCLib

2.1

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Other Mods

```shell
https://imgur.com/a/fwfWhb7
```

**Comment by icedmacchiato14** [comment]
Here is a picture of all the mods I have installed
[https://imgur.com/a/fwfWhb7](url)

**Comment by drakolordx7** [comment]
Little elaboration as well, did some more testing, I tested with no other mods and random worlds, seems to be solely in the soul sand valley, I went in manually and changed all "ruby" options in the generator.json to 2 vein count and 4 vein size and that worked great, no more ruby unfairly spawning.

**Comment by quiqueck** [comment]
Changed in BetterNether 7.1.1
