### ISSUE TITLE
Add more customization to betterx world type settings for the Nether [Suggestion] 

### ISSUE THREAD

**Issue by MCCrafter247** [quiqueck/BetterNether#62]
### Description

With Better End, you are able to edit the average biome sizes to adjust them to your liking. Why not also do this with Better Nether?

![unknown](https://user-images.githubusercontent.com/108512960/193638405-b4824717-b44a-4db9-8f0e-0e34848869c6.png)

This is Better Nether's current settings.

![unknown](https://user-images.githubusercontent.com/108512960/193638552-38ff8abb-fa9c-4981-adff-fff805964319.png)

This is Better End's current settings. Compared to this, Better Nether's settings feels very lacking. I love the customization potential you have for the end, and wish this same potential could be applied to the Nether. Being able to adjust the biome sizes would allow for some interesting Nether generation.

**Comment by quiqueck** [comment]
Released with BetterNether 7.1.2. Please re-open this issue if there was more you wanted to see.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/280847/202243340-a94f2771-c6d4-4d10-b3f8-591cdb3fc087.png">
