### ISSUE TITLE
[Suggestion] Have Ancient Debris spawn in Nether biomes where Netherrack is replaced with other blocks

### ISSUE THREAD

**Issue by SatDog92** [quiqueck/BetterNether#63]
### Description

In the current 7.1.0 version of this mod, it seems that the biomes that replace all Netherrack other blocks also replace Ancient Debris (examples: Soul Plain, Nether Swampland with the variants, Flooded Deltas). I also used an X-Ray resource pack to make sure there weren't any kind of ore in them. I see these biomes can remove ores and be unique in their resources, but i don't think Ancient Debris should be deleted from them.

**Comment by quiqueck** [comment]
Accepted, and added to the Enhancement Project. I will post here when there are any updates.
