### ISSUE TITLE
[1.18.2 and 1.19] Properly tag betternether's biomes as nether with biome tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [quiqueck/BetterNether#7]
### What happened?

Continuing from this PR: https://github.com/paulevsGitch/BetterNether/pull/561 and similar to https://github.com/quiqueck/BetterEnd/issues/9

Since the introduction of biome tags in 1.18.2, biome mods should tag their biomes with proper biome tags. BetterNether's biomes should be in the minecraft:is_nether biome tag for both 1.18.2 and 1.19.

Paul mentioned that the tags in Better X mods do not use json for tags so I cannot move my PR over to here as it won't be accepted it seems.

### BetterNether

7.0.2

### BCLib

2.0.5

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Thanks for reportin. this is a bug, as they actually should already have that tag.

**Comment by quiqueck** [comment]
I just checked, and as far as I can see, BN Biomes (at least in 1.19) are properly added to the `minecraft:is_nether`-Tag. But maybe I am testing this wrong... How did you discover that they are missing?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/280847/173915217-0b41701a-cbb9-4608-81e3-d3b3b464b80f.png">

**Comment by TelepathicGrunt** [comment]
I got a user back in 1.18.2 asking why my nether structures were not spawning in better nether biomes at all. I opened up the jars for the better x mods as I assumed they would do json tags like most mods do. Couldn’t find any biome tag so I went and made a datapack to manually add better nether biomes to the biome tag. The user reports that they were able to find my structures in the biomes with the datapack on.

My mod is using vanilla’s json structure system which uses biome tags to know which biome to add the structure to. 

Perhaps it was a coincidence/misunderstanding as to why it wasn’t working or it’s a bug in 1.18.2 better x mods if you’re checking in 1.19. At the time, I had no prior knowledge that better x mods squeeze in the biomes into the tags within code instead of json which is extremely confusing for modders and users alike trying to determine what tags a mod has

**Comment by quiqueck** [comment]
Yeah, it is easier for us to manageTag-Definitions in code, as it allows us to automate things. What mod are you developting. I can test with it to make sure our tags are handled properly.

**Comment by TelepathicGrunt** [comment]
My mod is Repurposed Structures. It is stable on 1.18.2. Currently I have ported it to 1.19 but as beta as there’s some issues I still need to work out.

**Comment by quiqueck** [comment]
A Great Mod :)

I know it is a singular workaround for the issue with programmatically Tags. But BCLib lets you export the Tags to better see what is going on. Simply run the command `/bclib dum_datapack` and the tag-information (along with some other useful stuff) is written to `bclib_datapack_dump` in your Minecraft Folder
