### ISSUE TITLE
Question about Nether Sakura trees

### ISSUE THREAD

**Issue by Gamemassa** [quiqueck/BetterNether#74]
### Description

I'm just curious, is it normal for Nether Sakura to grow upward through the ceiling it's planted on? (Screenshots below are of a "planter" I built in my friend's server) If that's normal, then no big deal, but I keep having to go back and grab more Netherrack to fill in the gaps between replantings and it would be nice to not have to, so I just figured I'd ask.

![2022-11-03_19 40 36](https://user-images.githubusercontent.com/18667108/199855383-eab1cb6b-4991-4371-b6d9-d236135eec56.png)

![2022-11-03_19 40 46](https://user-images.githubusercontent.com/18667108/199855397-63c28271-68d2-464d-a846-d7a9e2756d13.png)

**Comment by ChristopherJ123** [comment]
Also i think the saplings are not broken after growing the tree

**Comment by Gamemassa** [comment]
> Also i think the saplings are not broken after growing the tree

I actually thought that was a pretty cool effect that could be useful as its own mod.

**Comment by ChristopherJ123** [comment]
> I actually thought that was a pretty cool effect that could be useful as its own mod.

That's too overpowered imo.

**Comment by Gamemassa** [comment]
> > I actually thought that was a pretty cool effect that could be useful as its own mod.
> 
> That's too overpowered imo.

Yeah, sounds like they patched that.

**Comment by quiqueck** [comment]
Yes, the seed thing should be fixed, and yes, the sakura currently grows some roots that will penetrate a 1 thick floor layer.
