### ISSUE TITLE
[Bug] Infinite Boot Loop

### ISSUE THREAD

**Issue by ProjectKaos** [quiqueck/BetterNether#76]
### What happened?

Whenever I use BetterNether/End Minecraft loads into the menu but gets stuck at the red Mojang loading screen with the loading progress bar and keeps loading to 100% over and over in an infinite cycle. I am unable to use these mods because of this. I cannot even access the menu.

All mods/games/launchers are up-to-date. I suspect a mod incompatibility but no matter which mod I use or even have them on their own it doesn't work. 

No log crash file to give as I have to ALT+F4 out of the game to get out of the infinite boot cycle.

### BetterNether

The Latest

### BCLib

The latest

### Fabric API

The Latest

### Fabric Loader

The Latest

### Minecraft

1.19.2

### Other Mods

```shell
Iris
Sodium
Lithium
ClothConfig
Continuity
Croptopia
EntitityCulling
FabricApi
FriendsAndFoes
JEI
JER
LambDynamicLgihts
ModMenu
ReeesesSodiumOptions
SodiumExtra
Starlight
TechReborn
XaerosMinimap
YoureInGraveDanger
Architecturity
BCLib
```

**Comment by quiqueck** [comment]
Thanks for contacting us. Could you please post the _latest.log_ file here at GitHub. It should could contain some more Information that will help us narrowing down the issue.
