### ISSUE TITLE
Textures broken for vines and other plants

### ISSUE THREAD

**Issue by DARToe** [quiqueck/BetterNether#77]
### What happened?

All the vines in the Better Nether mod along with a few other plants all have broken textures. What it looks like is the texture sheet was miss aligned and is how showing mini versions of vanilla textures along with textures from other mods. The same thing is going on with several vines from the Better End mod as well. Better End is version 1.1.1
![2022-11-06_16 55 01](https://user-images.githubusercontent.com/117604008/200197784-8507dc68-194b-4dea-ad2c-e08e85c4bb4e.png)

![2022-11-06_16 55 20](https://user-images.githubusercontent.com/117604008/200197806-02fd1713-8bae-4a9e-ac56-31dfa299efdb.png)

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.59.1

### Fabric Loader

0.14.9

### Minecraft

1.18.2

### Other Mods

```shell
Here is a link to the mod pack I am using: https://www.curseforge.com/minecraft/modpacks/sirloin-shack-mods
```

**Comment by DARToe** [comment]
Sorry I forgot to mention this when I posted this report. But whenever a mod is updated, removed, added or anything else that may change the load order this bug temporarily fixes. If the game is launched with no change to the current mods the textures will bug out again.

**Comment by Ibaudia** [comment]
Having the same issue. Reinstalling the mod worked for a while and no longer does. Happens on multiple setups and instances. 1.19.2.

**Comment by quiqueck** [comment]
Thanks for reporting. Do you both use the same ModPack (sirloin-shack-mods)?

Since this is not a problem in my usual testing, there is not much I can do in order to find the issue. I know it is tedious, but did you try to borrow down which other mod is introducing the issue? That would help me to narrow down the underlying issue.

**Comment by Ibaudia** [comment]
I used my own modpack that's published on Modrinth, Sherman's Adventure Pack. I have not done that, but I will continue testing and report if I find anything.

**Comment by quiqueck** [comment]
From the ModPack mentioned in the original issue, I would try to disable 'Cull Leaves'. I do not test with that mod, and it sounds like it could alter some plant related properties. To make it clear, this is pure guess work based on the Mod description and the observed behaviour.

**Comment by Ibaudia** [comment]
I tried disabling OTBYG and that seems to have worked. It pops in randomly on new installations, though, it just hasn't happened after disabling BYG.

**Comment by quiqueck** [comment]
hm, one of my testing world contains BYG, and I did not see this issue as of yet...

**Comment by DARToe** [comment]
It is not BYG as the bug still accurse on a world with out it for me, is not Cull Leaves either tested that one as well. Also we may be encountering the same glitch caused by different things as I am using 1.18.2 while Ibuadia is using 1.19.2. But that is just a throwaway guess.

**Comment by DARToe** [comment]
Went through the mod lists on both packs and found all the ones that are the same:
Illuminations
-Effective
-BetterNether & BetterEnd
-Oh the Biomes You'll Go
-Fabric Waystones
-YUNG's better structure mods of somekind
-Sodium & Indium
This may help or it may not don't know.

**Comment by quiqueck** [comment]
The only ones I am not regular testing are Indium and YUNG's Mods. The other ones are also on my test world. But I think the latest version of Effective (or Illuminations) said, that both projects merge and I haven't tested those in the latest one. So that may be a candidate to disable for a test.

**Comment by Ibaudia** [comment]
Effective was giving me a lot of other issues in its latest update with printing "false" for millions of lines in log files. I used an older version of Effecive and Illuminations, then added back BYG and that appears to have fixed it, at least for now.

**Comment by DARToe** [comment]
They both have the same effect as all other mods for me. With it fixing then breaking again when the game is loaded without a change to the mod list.
