### ISSUE TITLE
[Bug] Ores do not drop when using Hephaestus tools

### ISSUE THREAD

**Issue by DCobley** [quiqueck/BetterNether#78]
### What happened?

When using a tool from Hephaestus (a Tinkers' Construct Fabric port) on ores from BetterNether, it doesn't drop anything. Used a Hephaestus pickaxe with the Netherite harvest tier, a normal Netherite pickaxe dropped successfully.

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.59.0

### Fabric Loader

0.14.9

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Hi, and thanks for reporting. Did you already talk to the Hephaestus Team? From the description, this appears to be an issue with the provided tolls (as other Modded-Tools like Gobber2-ones appear to work as they should)

**Comment by JackoDynamics** [comment]
I'm having the same issue with Hephaestus, on 1.20.1, I've just submitted a issue report on their github
