### ISSUE TITLE
[Bug] All non-sword tools from the mod have the same combat-related stats as the pickaxes

### ISSUE THREAD

**Issue by drown3d** [quiqueck/BetterNether#80]
### What happened?

Every tool that's not a sword has the same attack damage and speed as the pickaxes. The correct values should be as follows:
Cin. Axe: 9 dmg, 0.9 spd
Cin. Shovel: 4.5 dmg, 1.0 spd
Cin. Hoe: 1 dmg, 3.0 spd
Cin-Dia. Axe: 9.5 dmg, 1.0 spd
Cin-Dia. Shovel: 6 dmg, 1.0 spd
Cin-Dia. and Ruby Hoes: 1 dmg, 4.0 spd
Ruby Axe: 10 dmg, 1.0 spd
Ruby Shovel: 6.5 dmg, 1.0 spd
![image_2022-11-07_125229046](https://user-images.githubusercontent.com/85593395/200391228-5777f94a-4876-4bf7-8144-a44c0f993ab3.png)
![image_2022-11-07_125247132](https://user-images.githubusercontent.com/85593395/200391285-5634846b-5655-4365-9bec-880cbdbc5420.png)
![image_2022-11-07_125316884](https://user-images.githubusercontent.com/85593395/200391355-1b8f780f-7a0e-4d02-9378-6f3750112989.png)
![image_2022-11-07_125347624](https://user-images.githubusercontent.com/85593395/200391450-cbf3f3bc-f7d1-4349-8057-4f4f387b3ec1.png)
![image_2022-11-07_125408383](https://user-images.githubusercontent.com/85593395/200391507-b6b20323-7cc0-4cd5-a296-62491947b495.png)

### BetterNether

6.1.2

### BCLib

1.4.7

### Fabric API

0.59.0

### Fabric Loader

0.14.9

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Released with BetterNether 7.1.2. Not sure if I'll find the time to back port this to the 6.x-Versions.

**Comment by drown3d** [comment]
I see now that this newer version addressed everything being essentially a pickaxe, but now they are very overpowered, compared to even BYG's pendorite or DragonLoot.

Their attack speed might be fine as is but please adjust their damage accordingly.
