### ISSUE TITLE
[Suggestion] I want to advertise your BetterNether mod to MCBBS.

### ISSUE THREAD

**Issue by imnotyangjiu** [quiqueck/BetterNether#81]
### Description

The BetterNether mod is nice and it helps me a lot!

I am a Chinese player and I like your mod "BetterNether".

Could you please allow me to translate your mod and advertise it to MCBBS?

You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.

I'll NEVER claim it as mine and mark you as the author .

Looking forward that you can make more and more good mods!

**Comment by quiqueck** [comment]
Could you please provide more detail what MCBBS is?

**Comment by imnotyangjiu** [comment]
Hi.MCBBS is the largest Minecraft forum in China.People in MCBBS can contact me for suggestion or reporting bugs in Chinese, and then I can contact you in English.We can make this mod better and better together.Thank you!

**Comment by quiqueck** [comment]
Sure thing, that would be quite helpful :)
