### ISSUE TITLE
[Bug] Nether Ruby Armor lights user on fire

### ISSUE THREAD

**Issue by SivyxDev** [quiqueck/BetterNether#86]
### What happened?

The Nether Ruby armor lights its user on fire when the user takes damage from a distinct entity source. 

Expected behavior is to not be lit on fire, or to not take damage from said fire.

### BetterNether

7.1.2

### BCLib

2.1.3

### Fabric API

0.66.0

### Fabric Loader

0.14.10

### Minecraft

1.19.2

**Comment by SivyxDev** [comment]
Update - after further (unintended) testing, it seems to only affect zombies or other hostile/neutral enemies that attack you with melee. I assume its setting you on fire due to the main game feature of a zombie on fire transferring the on-fire state to the player.

**Comment by quiqueck** [comment]
Yeah, you probably catch fire from the attacker. That would not be a bug, but simply a disadvantage of the enchantment.
