### ISSUE TITLE
[Bug] REI doesn't show recipes and CT can't modify the recipes

### ISSUE THREAD

**Issue by Cynicizm** [quiqueck/BetterNether#87]
### What happened?

This mod, along with BetterEnd, is not integrable with ~~REI~~ and CraftTweaker:

~~1. I can't see any item recipe from BetterEnd and BetterNether using REI. This is extremely frustrating, because your mod introduces a WHOLE LOT of items, yet players can't see their recipes through REI.~~ 
**Reinstalled the mods and all recipes appear again in REI.** ~~Tweaking any recipe with CraftTweaker will result in all recipes being inaccessible again via REI.~~ **Reloading the game causes all recipes to be inaccessible in REI until I restart my world.**

2. Crafting/smelting/smithing/etc recipes can't be removed/modified AT ALL with CraftTweaker (CT). I want to remove some items but disabling things in your config just lead to crash on boot (see https://github.com/quiqueck/BetterEnd/issues/110 and https://github.com/quiqueck/BetterNether/issues/70, where you still haven't done anything to fix those issues), so the only logical solution is by using CT. Unfortunately, it doesn't work too. I tried removing the recipe of an item using CT, but when I try to craft it in crafting table, it still produces the item that has the removed recipe, and REI now won't show ANY RECIPE of BetterEnd & BetterNether.

This mod has amazing content. Too bad the configurability side has always been neglected. It's like the author doesn't want player to tweak things according to their preference, and it's just plain disappointing for me (and I'm sure, a lot of others too). 

Please do something about this.

### BetterNether

7.1.2

### BCLib

2.1.4

### Fabric API

0.67.1

### Fabric Loader

0.14.10

### Minecraft

1.19.2

### Relevant log output

Logs are irrelevant for this particular problem.

### Other Mods

Roughly Enough Resources (REI), CraftTweaker (CT)

**Comment by quiqueck** [comment]
As you found, REI should work just fine.

The current Versions of BN/BE inject recipes at runtime, which is probably not something that CT does/can handle. The 1.19.3 Releases will eventually change recipes to get loaded from a builtin datapack, which should fix that issue.
