### ISSUE TITLE
[Bug] Nether wood type boats are spawning regular oak type boats

### ISSUE THREAD

**Issue by ZeroneV0** [quiqueck/BetterNether#92]
### What happened?

While trying to summon a nether type boat it creates just oak boats.
Tried to change some texture files, but nothing happened. Examined that these boats have empty BalmData in nbt tags.
![2022-12-06_21 42 07](https://user-images.githubusercontent.com/90704648/205995313-fb8de756-7235-442e-8f78-e1f67962dd66.png)

### BetterNether

7.1.1

### BCLib

2.1.2

### Fabric API

0.64.0

### Fabric Loader

0.14.10

### Minecraft

1.19.2

### Other Mods

```shell
1.19.2-Effective-Crystals-1.1.jar
1.19.2-YUNG-s-API-v3.8.2-Fabric.jar
1.19.2-YUNG-s-Better-Desert-Temples-v2.2.1-Fabric.jar
1.19.2-YUNG-s-Better-Dungeons-v3.2.1-Fabric.jar
1.19.2-YUNG-s-Better-Mineshafts-v3.2.0-Fabric.jar
1.19.2-YUNG-s-Bridges-v3.1.0-Fabric.jar
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
AdditionalAdditions-5.1.0.jar
AdditionalStructures-v.4.1.0-1.19.2.jar
AdvancementPlaques-1.19.2-fabric-1.4.6.jar
BOMD-1.4.3-1.19.2.jar
BSS-fabric-1.19.2-v1.4.3.jar
BedBenefits-Fabric-1.19.2-9.1.2.jar
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar
BetterAnimationsCollection-v4.0.4-1.19.2-Fabric.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
BetterThirdPerson-Fabric-1.19-1.8.1.jar
BiomeParticleWeather-v4.0.0-1.19-Fabric.jar
BiоmеsInJаrs-v1.1.1-MC-1.19-1.19.2-Fabric.jar
Bookshelf-Fabric-1.19.2-16.1.11.jar
BountifulFabric-4.0.0.jar
CITResewn-1.1.2+1.19.2.jar
CameraOverhaul-1.3.1-fabric-universal.jar
Chunky-1.3.38.jar
CosmeticArmor-1.19-1.4.0.jar
CreativeCore_FABRIC_v2.8.5_mc1.19.2.jar
Croptopia-1.19.2-FABRIC-2.1.2.jar
Dave-s-Potioneering-0.9-Fabric-1.19.2.jar
Decorative+Blocks-fabric-1.19.2-3.0.0.jar
DeeperAndDarker-Fabric-1.19-1.1.4.jar
DungeonCrawl-1.19-2.3.11.jar
DungeonsArise-1.19-2.1.51-fabric-beta-hf.jar
DynamicSurroundings-RemasteredFabric-1.19-0.1.0.jar
EasyAnvils-v4.0.5-1.19.2-Fabric.jar
EasyMagic-v2.0.2-1.19.2-Fabric.jar
Ecologics-2.1.10-Fabric-1.19.2.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.8.jar
Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
EquipmentCompare-1.19-fabric-1.3.1.jar
Essential-fabric_1-19(1).jar
FABRIC-1.19.2-ArmorStatues-v4.0.1.jar
FABRIC-1.19.2-EasyAnvils-v4.0.5.jar
Fabric-1.19.2-SmoothSwapping-0.4.6.jar
Fabric-Swampier-Swamps-1.19-1.1.0.jar
FallingTree-1.19.2-3.10.0.jar
Fastload-1.2.1.jar
ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
Galosphere-1.19.2-1.2.0-FABRIC.jar
Gobber2-Fabric-1.19.2-2.6.56.jar
Iceberg-1.19.1-fabric-1.0.46.jar
Incendium-v5.1.3a-1.19.2.jar
InvMove-1.19-0.8.1-Fabric.jar
InventoryHUD-fabric-[1.19.1]+-3.4.2.jar
Jade-1.19.3-fabric-9.0.0.jar
Kambrik-4.0-1.19.2.jar
LegendaryTooltips-1.19.2-fabric-1.3.3.jar
MineMenuFabric-6.3.0-1.19.2.jar
Minimalistic+Bridging-1.19-1.1.0.jar
MiningDimensions_Fabric-1.19.2-1.4.27.jar
MissingWilds-fabric-1.19-1.1.2.jar
MmmMmmMmmMmm-FABRIC-1.18-1.5.3.jar
MoreMetalBars-1.0.0.jar
Neat-1.19-32-FABRIC.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar
Origins-1.19.2-1.7.1.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.5.0+1.14.4-1.19.2.jar
PresenceFootsteps-1.6.2.jar
Prism-1.19.2-fabric-1.0.3.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
Reaper-1.0.2-1.19.2-fabric.jar
RoughlyEnoughItems-9.1.555.jar
SlotCycler-v4.0.2-1.19.2-Fabric.jar
Spirit-fabric-1.19.2-2.2.2.jar
Strawgolem-fabric-1.19-2.0.0b2.jar
Structory-1.19-v1.3.jar
TerraBlender-fabric-1.19.2-2.0.1.128.jar
Terralith_v2.3.5.jar
TheExtractinator-1.10.jar
The_Graveyard_2.0_(FABRIC)_for_1.19.2.jar
The_Graveyard_Biomes_1.2_(FABRIC)_for_1.19.jar
Towns-and-Towers-1.19.2-1.9.jar
TravelersTitles-1.19.2-Fabric-3.1.0.jar
VisualWorkbench-v4.2.0-1.19.2-Fabric.jar
Wall-Jump-UNOFFICIAL-Fabric-Forge-Quilt-v1.6.1b-1.19.2.jar
XaerosWorldMap_1.28.1_Fabric_1.19.1.jar
Xaeros_Minimap_22.16.0_Fabric_1.19.1.jar
YetAnotherConfigLib-1.6.0.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
Zoomify-2.8.0.jar
adventurez-1.4.17.jar
amecs-1.3.8+mc.1.19-rc2.jar
appleskin-fabric-mc1.19-2.4.1.jar
architects-palette-fabric-2.1.1.jar
architectury-6.3.49-fabric.jar
arrp-0.6.4.jar
auditory-0.0.3-1.19.x.jar
autohud-2.3.1+1.19.1.jar
autotag-2.0.0+1.19.jar
balm-fabric-4.5.2+0.jar
better-end-2.1.1.jar
betterbeds-1.2.0.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
bettercombat-fabric-1.4.5+1.19.jar
bewitchment-1.19-6.jar
biomeinfo-1.19.2-12.jar
bobby-4.0.0.jar
borderless-mining-1.1.5+1.19.jar
bucolicorigins-3.5.jar
camerautils-1.19.2-1.0.2.jar
cardinal-components-api-5.0.2.jar
carpet-fixes-1.19-1.12.2.jar
cem-0.7.1.jar
chat_heads-0.7.1-fabric-1.19.1.jar
cherishedworlds-fabric-6.0.1+1.19.2.jar
clickthrough-1.19.1-fabric0.58.5-0.4.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.11.jar
combatroll-fabric-1.0.8+1.19.jar
comforts-fabric-6.0.2+1.19.2.jar
completeconfig-2.0.0.jar
continuity-2.0.1+1.19.jar
cr-compass-ribbon-fabric-2.8.2+1.19.1.jar
crafting-bench-0.1-ALPHA1.19.jar
create-fabric-1.19.2-0.5.0f-776.jar
creeperoverhaul-2.0.5-fabric.jar
croptopia-chocolaterie-1.2-1.19.jar
dark-loading-screen-1.6.12.jar
dcch-1.2.jar
do-a-barrel-roll-2.2.0+1.19.2-fabric.jar
dragonloot-1.1.2.jar
drinkbeer-3.2.2-1.19.2.jar
dualwielding-1.1.2.jar
dungeon_difficulty-1.1.1+1.19.jar
dynamic-fps-2.2.0.jar
dynamic-music-1.5.1.jar
dynamiccrosshair-3.9+1.19.jar
dynamiccrosshair-compat-1.9+1.19.2.jar
eden-ring-0.6.4.jar
effective-1.3.jar
emoji-type-2.0.1+1.19.jar
emotecraft-for-MC1.19.2-2.2.5-fabric.jar
enderitemc-enderitemod-1.4.1-1.19.jar
enderscape-0.3.5-1.19.1.jar
entity_texture_features_fabric_1.19.x-4.1.1.jar
entityculling-fabric-1.5.2-mc1.19.jar
environmentz-1.3.3.jar
everycomp-1.19.2-2.0.10.jar
expandeddelight-0.2.2.jar
expert_armor-2.1.7.jar
expert_weapons-2.1.6.jar
extraalchemy-fabric-1.19.2-1.9.0.jar
extrakeybinds-0.4.0+1.17-1.19.2.jar
extraorigins-1.19-2.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabric-api-0.64.0+1.19.2.jar
fabric-carpet-1.19.2-1.4.84+v221018.jar
fabric-end-remastered-5.2.0.jar
fabric-language-kotlin-1.8.5+kotlin.1.7.20.jar
fabricskyboxes-1.19.2-0.5.8.jar
fallingleaves-1.12.2+1.19.2.jar
fallingleaves-1.12.4+1.19.2.jar
farmers-delight-fabric-1.19.X-1.3.3.jar
farmersknives-2.1.jar
ferritecore-5.0.0-fabric.jar
firstperson-fabric-2.2.0-mc1.19.2.jar
forcecloseloadingscreen-1.1.1.jar
forgetmechunk-1.0.4-1.18.X-1.19.X.jar
frame-fabric-0.26.0+1.19.jar
geckolib-fabric-1.19-3.1.37.jar
gipple-fabric-1.19-1.0.0.jar
guard-villagers-fabric-1.19.2-1.0.16.jar
guiclock-fabric_1.19.2-3.8.jar
illuminations-1.10.11.jar
immersive_armors-1.4.2.jar
immersive_weathering-1.19.2-1.2.4-fabric.jar
impaled-1.1.4.jar
indium-1.0.9+mc1.19.2.jar
infusion-table-mod-1.1.0.jar
interactic-0.1.11+1.19.jar
inventorymanagement-1.0.01.19.jar
iris-mc1.19.2-1.4.0.jar
jobsaddon-1.0.4.jar
keymap-0.6.0-beta.0+1.19-fabric.jar
konkrete_fabric_1.5.0_MC_1.19.1.jar
krypton-0.2.1.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.1.2+1.19.jar
lazydfu-0.1.3.jar
levelz+Compats.jar
levelz-1.4.0.jar
lithium-fabric-mc1.19.2-0.10.0.jar
malilib-fabric-1.19.2-0.13.0.jar
mcda-2.2.0.jar
mcdar-1.5.2-1.19.jar
mcdw-5.0.4-1.19.jar
medievalweapons-1.4.1.jar
midnightlib-fabric-1.0.0.jar
modmenu-4.0.6.jar
moonlight-1.19.2-2.1.3-fabric.jar
moonlight-1.19.2-2.1.9-fabric.jar
more-geodes-1.5.2.jar
moreculling-1.19.1-0.10.0.jar
moremobvariants-1.0.0-1.19.2.jar
morevillagers-fabric-1.19-4.0.2.jar
mousewheelie-1.10.2+mc1.19-pre1.jar
musicdr-3.0.0.jar
mythicmetals-0.16.3+1.19.2.jar
mythicmetals-decorations-0.4.1.jar
mythicupgrades-1.3+1.19.2.jar
naturalist-fabric-2.1.1-1.19.2.jar
niceload-0.1.3.jar
notenoughanimations-fabric-1.6.1-mc1.19.1.jar
numismatic-overhaul-0.2.3+1.19.jar
nyfsquiver-Fabric-0.5.1-1.19.2.jar
origins-plus-plus-1.7.2.jar
owo-lib-0.8.5+1.19.jar
pal-1.6.0.jar
passableleaves-1.3.0.jar
physics-mod-2.8.13a-mc-1.19.x-fabric.jar
pickupnotifications-1.0.31.19.jar
pickupnotifications-1.3.1+1.19.jar
pickyourpoison-1.0.11.jar
plasmovoice-fabric-1.19.1-1.2.19.jar
player-animation-lib-fabric-0.4.0-test1.jar
projectiledamage-fabric-2.2.0+1.19.jar
qfapi-4.0.0-beta.17_qsl-3.0.0-beta.19_fapi-0.64.0_mc-1.19.2.jar
realisticsleep-1.6.0.jar
reeses_sodium_options-1.4.7+mc1.19.2-build.59.jar
replanter-fabric-1.19-1.3(1).jar
rottencreatures-fabric-1.19.2-1.0.1.jar
show-me-your-skin-1.3.4+1.19.jar
sodium-extra-0.4.11+mc1.19.2-build.68.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.15.jar
supplementaries-1.19.2-2.2.20-fabric.jar
terrestria-5.0.3.jar
tiered-1.1.5.jar
tooltipfix-1.1.0-1.19.jar
travelers-backpack-1.19.2-8.2.7.jar
travelitelevelzaddon-1.0.0.jar
trinkets-3.4.0.jar
twigs-2.0.0-beta.9+1.19-fabric.jar
twilightforest-fabric-1.19.2-4.2.299.jar
ultris-v5.6.6a-fabric.jar
vectorientation-1.0.1a.jar
visuality-0.5.5.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.0-all.jar
voidz-1.0.9.jar
waystones-fabric-1.19-11.1.0.jar
weaponmaster-multi-fabric-1.19-3.0.2.jar
wraith-alloy-forgery-2.0.16+1.19.jar
xlpackets-2.1-1.17.1.jar
```

**Comment by quiqueck** [comment]
Summon as in using a command to create them?

**Comment by ZeroneV0** [comment]
No, just trying to place a boat from an item

**Comment by quiqueck** [comment]
Ok, I just re-checked and this appears to be working with my test mod selection. So this is probably a combat issue with some other mod.

For reference, this is the mod-list I am testing with:
- ad_astra 1.11.7
- additionaladditions 5.1.0
- additionalentityattributes 1.0.0+1.19 via apoli
- adorn 3.6.1+1.19
- advanced_runtime_resource_pack 0.6.2 via carrier
- advdebug 2.3.0
- adventurez 1.4.16
- animal_feeding_trough 1.0.3+1.19.2
- animal_origins_18 1.0.0
- apocalypse 0.2.27
- apoli 2.6.0 via origins
- appleskin 2.4.1+mc1.19
- aqupdgrizzly 1.19.2-1.3
- architectury 6.2.46
- badpackets 0.2.0
- betteranimalsplus 1.19-11.0.7
- betterf3 1.4.0
- blockus 2.5.2+1.19.2
- blue_endless_jankson 1.2.1 via owo
- blur 2.6.0
- bookshelf 16.1.6
- bosses_of_mass_destruction 1.4.3-1.19.2
- botarium 1.7.10
- byg 2.0.0.13
- caffeineconfig 1.0.0+1.17 via sodium-extra
- calio 1.7.0 via apoli
- capybara 1.0.8
- cardinal-components 5.0.2
- carrier 1.4.1
- chat_heads 0.7.1
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.2.88
- collective-fabric 5.7
- com_electronwill_night-config_core 3.6.6 via byg
- com_electronwill_night-config_toml 3.6.6 via byg
- com_eliotlash_mclib_mclib 19 via geckolib3
- com_eliotlash_molang_molang 19 via geckolib3
- com_github_llamalad7_mixinextras 0.1.0-rc5 via porting_lib_base
- com_google_code_findbugs_jsr305 3.0.2 via twilightforest
- com_typesafe_config 1.4.1 via croptopia
- comforts 6.0.2+1.19.2
- consularsorigins 1.7.1
- continuity 2.0.1+1.19
- croptopia 2.1.2
- customizableelytra 1.6.2-1.19
- darkpaintings 13.1.2
- decorative_blocks 3.0.0
- deepslatecutting 1.5.0
- dynamicsoundfilters 1.3.0+1.19
- ea 1.0.0
- ecologics 2.1.10
- edenring 0.6.4
- effective 1.3
- emi 0.4.3+1.19
- enchant_giver 1.3.0 via mcdw
- enchdesc 13.0.3
- enderscape 0.4.1-1.19.2
- extra_classes_origins 1.0.0
- extrakeybinds 0.3.0
- extraorigins 1.19-2
- fallingtree 3.10.0
- fiber 0.23.0-2 via collective-fabric
- forgeconfigapiport 4.2.6
- forgotten_features 1.6+1.19.2
- freecam 1.1.6
- fwaystones 3.0.5+mc1.19.2
- geckolib3 3.1.22
- geodes 1.5.1
- gobber2 2.6.51
- goblintraders 1.5.2
- graveyard 2.0
- here-be-no-dragons 1.0.0 via twilightforest
- herobrine 3
- illuminations 1.10.8
- immersive_weathering 1.19.2-1.2.3
- indium 1.0.9+mc1.19.2
- inventoryprofilesnext 1.8.5
- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
- io_leangen_geantyref_geantyref 1.3.11 via croptopia
- iris 1.4.2
- jamlib 0.4.4
- jankson 4.1.1+j1.2.1 via libgui
- java 17
- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
- jump 1.0.0
- kanos_config 0.3.1+1.14.4-1.19 via pehkui
- lank 1.0.0
- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
- libipn 1.0.5
- libninepatch 1.1.0 via libgui
- lightoverlay 7.0.0
- lightsaber 0.1.6d
- lithium 0.9.1
- logicgates 1.3.5
- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
- mavm 1.1.0
- maybe-data 1.3.2-1.19.2 via deepslatecutting
- mcda 2.2.0
- mcdar 1.5.2-1.19
- mcdw 5.0.4-1.19
- mcwbridges 2.0.5
- mcwdoors 1.0.7
- mcwfences 1.0.6
- mcwlights 1.0.4
- mcwtrpdoors 1.0.7
- mcwwindows 2.0.3
- medievalorigins 1.19.x-4.1.3
- megaparrot 1.0.7-1.19.2
- midnightlib 0.5.2 via effective
- minecraft 1.19.2
- mm 2.3 via enderscape
- moborigins 1.9.0
- modmenu 4.1.1
- moonlight 1.19.2-2.1.9
- moreflowerpots 3.0-SNAPSHOT
- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
- mypack 1.0.0
- nears 1.2.3
- obsidianequipment 1.0.4
- omega-config 1.2.2-1.18.1 via graveyard
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.10.1 via iris
- org_joml_joml 1.10.4 via sodium
- org_spongepowered_configurate-core 4.1.2 via croptopia
- org_spongepowered_configurate-hocon 4.1.2 via croptopia
- origins 1.7.0
- origins-classes 1.4.0
- owo 0.8.4+1.19
- patchouli 1.19.2-76-FABRIC
- pehkui 3.5.0+1.14.4-1.19.2
- player_transport_ducts 1.0.2
- playerabilitylib 1.6.0 via apoli
- plushies 1.2
- porting_lib_accessors 2.0.547+1.19.2 via porting_lib_extensions
- porting_lib_attributes 2.0.547+1.19.2 via porting_lib_extensions
- porting_lib_base 2.0.547+1.19.2 via template
- porting_lib_common 2.0.547+1.19.2 via porting_lib_transfer
- porting_lib_constants 2.0.547+1.19.2 via porting_lib_transfer
- porting_lib_entity 2.0.547+1.19.2 via template
- porting_lib_extensions 2.0.547+1.19.2 via porting_lib_model_loader
- porting_lib_model_generators 2.0.547+1.19.2 via template
- porting_lib_model_loader 2.0.547+1.19.2 via porting_lib_obj_loader
- porting_lib_models 2.0.547+1.19.2 via template
- porting_lib_networking 2.0.547+1.19.2 via template
- porting_lib_obj_loader 2.0.547+1.19.2 via template
- porting_lib_tags 2.0.547+1.19.2 via template
- porting_lib_transfer 2.0.547+1.19.2 via template
- pugh_lib 1.4.15 via gobber2
- pugh_tools 1.3.22 via gobber2
- reach-entity-attributes 2.3.0 via twilightforest
- reeses-sodium-options 1.4.7+mc1.19.2-build.59
- resourcefullib 1.1.17
- satin 1.8.0 via blur
- sculksieg 1.0.0
- serialization_hooks 0.3.22 via twilightforest
- shulkerboxtooltip 3.1.3+1.19.2
- simple_backpack 1.3.25
- skylorlib 1.5.1
- sodium 0.4.4+build.18
- sodium-extra 0.4.11+mc1.19.2-build.68
- sparkle 1.0.3
- spectrelib 0.10.0+1.19 via comforts
- stoneholm 1.4.4
- supplementaries 1.19.2-2.2.22
- survivalplus 0.1.6g
- t_and_t 1.8.2
- team_reborn_energy 2.2.0 via botarium
- template 2.0.547+1.19.2 via twilightforest
- terrablender 2.0.1.130
- terraform-wood-api-v1 4.1.0 via blockus
- thonkutil 2.15.4+1.19
- thonkutil-base 1.13.2+4a8c408a57 via thonkutil
- thonkutil-capes-v1 1.4.2+3eb2749857 via thonkutil
- thonkutil-coords-v1 1.1.2+8ff533c957 via thonkutil
- thonkutil-customization-v1 1.1.2+8ff533c957 via thonkutil
- thonkutil-legacy 1.1.2+5d4263f557 via thonkutil
- thonkutil-modchecker-v1 1.1.3+bd4b387957 via thonkutil
- thonkutil-potions-v0 1.5.2+8ff533c957 via thonkutil
- thonkutil-titlescreen-v1 1.2.2+8ff533c957 via thonkutil
- thonkutil-trades-v1 1.2.2+8ff533c957 via thonkutil
- toolstats 12.0.2
- travelersbackpack 1.19.2-8.2.2
- trinkets 3.4.1
- twilightforest 4.2.299
- unvotedandshelved 2.0.3
- vanilla_degus 1.3.2
- villagernames 4.0.9
- visuality 0.5.1
- wthit 5.13.4
- wunderreich 3.0.18
- xaerominimap 22.16.2
- xaeroworldmap 1.28.3
- yigd 1.4.4
