### ISSUE TITLE
Strange Issue with advancements for both BetterNether and BetterEnd

### ISSUE THREAD

**Issue by Gamerbolts** [quiqueck/BetterNether#93]
### What happened?

Hello! I was testing out my modpack, whenever I gave myself an item from either betternether or betterend I got a strange advancement in my chat log
![image](https://user-images.githubusercontent.com/20451601/206012135-8312e430-afff-4fa2-a8da-41d10dbc2963.png)
Here is the log if that helps. 
[latest.log](https://github.com/quiqueck/BetterNether/files/10169972/latest.log)

### BetterNether

7.1.2

### BCLib

2.1.4

### Fabric API

0.68.0

### Fabric Loader

0.14.10

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
Recipe advancements should not show up in your logs. Those Advancements are used internally to bring up the little notification that tells you which recipes you have now unlocked in your recipe book.

The are also generated by the vanilla game when you (for example) get hold of the first piece of wood. I would assume that some other mod does not recognise those types of advancements when they are generated in a non vanilla namespace (`advancements.betternether.recipes` vs. `advancements.minecraft.recipes`).

**Comment by SplendidAlakey** [comment]
Without looking at the logs, I'm pretty sure its Clickable Advancements. There's a config option to disable these extra messages from showing up.

**Comment by Gamerbolts** [comment]
Having so many mods I must have overlooked that config option. Thank you!
