### ISSUE TITLE
[Suggestion] Add c:ores tag to all ores

### ISSUE THREAD

**Issue by SplendidAlakey** [quiqueck/BetterNether#94]
### Description

In order to avoid having duplicate issues open, this is going to be a 2 in one feature request, for BetterEnd and BetterNether, because they both are missing common tags for ores, which prevents it from working with other mods.

In my case, I wanted to add compatibility with [Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement), however, it didn't work, even when I manually added the ores to the tag collection via a datapack and/or KubeJS: https://github.com/MoriyaShiine/enchancement/issues/70. Datapacks fail to apply tags to BetterX ores altogether; KubeJS does seem to be able to add a tag, but it doesn't help in this scenario, for some reason.

So, ideally, the tags should be added natively by both BetterEnd and BetterNether to avoid any such issues.

**Comment by quiqueck** [comment]
Thanks for notifying me. Will get added to the upcoming release of the 1.19-Versions

**Comment by SplendidAlakey** [comment]
Just tried it out, it worked for every ore, except for `betternether:nether_redstone_ore`. Could you, please, take a look at it? 

Also the tags themselves are not visible in F3+H, not sure why. Doesn't seem to affect functionality, though.

**Comment by quiqueck** [comment]
Ah, right. That is another base class. Will be fixed in the next release of BetterNether

**Comment by quiqueck** [comment]
Just released the fix for the 1.19.3 version, will also be included in the next release for older 1.19 versions
