### ISSUE TITLE
[Bug] The chat gets spammed with unlocked recipes

### ISSUE THREAD

**Issue by Emmet-v15** [quiqueck/BetterNether#96]
### What happened?

Recipes are being shown in the chat

![image](https://user-images.githubusercontent.com/36600912/207114482-1d2d55b9-d14c-4d03-b3cb-849ba3162ad2.png)
I'm pretty sure this isn't meant to be happening

### BetterNether

7.1.2

### BCLib

2.1.5

### Fabric API

0.69.0

### Fabric Loader

0.14.11

### Minecraft

1.19.3

### Relevant log output

```shell
Client log:
https://gist.github.com/Emmet-v15/0e78b1ba1c13b0a7863abd4eeb3146f1

Server log:
https://gist.github.com/Emmet-v15/152772d3b1f055886b7a1feda5baf8d2
```

**Comment by Emmet-v15** [comment]
This also happens on betterend

**Comment by Ayutac** [comment]
this happens because the (invisible via source code) recipe advancements have announce_to_chat set to true for some reason. Probably needs fixing in BLCRecipeManager or how it is called in betterx

**Comment by quiqueck** [comment]
In 1.19.3, recipes are added to the mods default datapack. Just checked the generated file, and it has this line:
https://github.com/quiqueck/BetterNether/blob/bad9c6eb2f5e0542741d126b2faf9b2c082d13a1/src/main/generated/data/betternether/advancements/recipes/decorations/warped_taburet.json#L36

That should be the correct setting, right?

**Comment by quiqueck** [comment]
Same goes when checking the runtime recipe generation:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/280847/215265611-70c8f5e5-6311-4fe2-bf96-f6065b888403.png">
